### ISSUE TITLE
how should python2.7 use this tool

### ISSUE THREAD

**Issue by ghost** [alexmojaki/heartrate#12]
Traceback (most recent call last):
  File "D:/mainV6_G10_for_wenqiang.py", line 25, in <module>
    import heartrate; heartrate.trace(browser=True)
  File "C:\Users\zhangwenqiang\AppData\Roaming\Python\Python27\site-packages\heartrate\__init__.py", line 1, in <module>
    from heartrate.core import trace
  File "C:\Users\zhangwenqiang\AppData\Roaming\Python\Python27\site-packages\heartrate\core.py", line 7, in <module>
    from functools import lru_cache
ImportError: cannot import name lru_cache

lru_cache does not seem to work with python2.7.

**Comment by alexmojaki** [comment]
Sorry, Python 2 just isn't supported.
